// Copyright 2026 Element Creations Ltd.
//
// SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
// Please see LICENSE in the repository root for full details.

// settings.gradle
pluginManagement {
    repositories {
        google()  // <-- This is required for AGP
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()      // For AndroidX, Material, etc.
        mavenCentral() // For Kotlin, JUnit, etc.
    }
}

include ':matrixrtc'
project(':matrixrtc').projectDir = new File(rootDir, 'matrixrtc')

